import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { gql, useQuery } from "@apollo/client";
import { useState } from 'react';
import { initializeApollo } from '../../lib/useApollo';
import { getUsers } from '@/hooks/getArticles';
import styled from 'styled-components';
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })

const QUERY_ARTICLES = gql`
  query {
    articles {
      id
      article_name
    }
  }
`;



export default function Home(props: any) {

  const { loading, error, data } = useQuery(QUERY_ARTICLES);
  console.log('ARTICLES', data?.articles);
  console.log('USERS', props.users);
  console.log('props', props);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>My First Next.js Page</Title>
      <StyledComponent>Green background</StyledComponent>



      <main className={styles.main}>
        APP MY
        {props.users.map((user: any, index: number) => {
          // eslint-disable-next-line react/jsx-key
          return <Link href={`products/${user.id}`} key={user.id}>{user.name}</Link>
        })}
        {data ? data.articles.map((user: any, index: number) => {
          // eslint-disable-next-line react/jsx-key
          return <div key={index}>{user.article_name}</div>
        }) : <></>}
      </main>

      {/* <button onClick={handleClick}>Load Articles</button> */}
    </>
  )
}

const Title = styled.h1`
  color: red;
`;

const StyledComponent = styled.div`
    background-color:green;
    font-size:30px;

`

export const getServerSideProps = async () => {

  const data = await getUsers();


  return {
    props: {
      users: data.users,
    },
  };
};


